apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: coit-backend
  labels:
    app: coit-backend
    runon: fargate
spec:
  selector:
    matchLabels:
      app: coit-backend
  replicas: 3                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        runon: fargate
        app: coit-backend                                  # 6
        app.kubernetes.io/name: coit-backend
    spec:
      containers:
        - image: basilvarghese/myapp-java:latest
          imagePullPolicy: IfNotPresent                         # 7
          name: coit-backend
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_NAME
              value: mydb
